[[PaStiX]]
arch = "aarch64"
git-tree-sha1 = "1bf940d2489fc70fbb28498cf4a68bbd91f681d7"
libgfortran_version = "5.0.0"
os = "macos"

    [[PaStiX.download]]
    sha256 = "0bd22504c61f3732523e0b2e1b502200a9f54a8df5e6d193f368ec4f0d25db09"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.3.2+0/PaStiX.v6.3.2.aarch64-apple-darwin-libgfortran5.tar.gz"
[[PaStiX]]
arch = "aarch64"
git-tree-sha1 = "28ba6d4546fea93c959c52ff63e91dfd34f58690"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "ca6df9728ca94d48dddd8748e3642d89f3f0f588ea467293f4934c088db6345a"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.3.2+0/PaStiX.v6.3.2.aarch64-linux-gnu-libgfortran4.tar.gz"
[[PaStiX]]
arch = "aarch64"
git-tree-sha1 = "05f5d8d98d26e487304ae5c43096ca8f8be9a437"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "1e6c7a157f8cbc74599d906e460a07165ca946eace81180d04a9e257eb82dc0b"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.3.2+0/PaStiX.v6.3.2.aarch64-linux-gnu-libgfortran5.tar.gz"
[[PaStiX]]
arch = "aarch64"
git-tree-sha1 = "3431687ebf41665e7dd3b27bf9c380f8ae382f77"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "65b98d394d3aa225351119c0aacc8ad4cce4730a8e4003e1687fa428979f92a4"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.3.2+0/PaStiX.v6.3.2.aarch64-linux-musl-libgfortran4.tar.gz"
[[PaStiX]]
arch = "aarch64"
git-tree-sha1 = "c2d303a43e09346c933cf5b9ef20fa8eca71c142"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "c35bc1faf2b98261c282a56cb26661b5d354d95d3fbb9d7459986716e5e9eb17"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.3.2+0/PaStiX.v6.3.2.aarch64-linux-musl-libgfortran5.tar.gz"
[[PaStiX]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a6752f29a4ccce2a6a6a69fe377289dc47324b80"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "63c2949118b419562ed123b2e4f1f9df2dd264cd181e48b1c34066cef55542fb"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.3.2+0/PaStiX.v6.3.2.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[PaStiX]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8cd0cea891894a9d488538d7f2f10286404e13f7"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "2e2b818a01fe96e2331f126b43a850df726076428d31ec2d120f950f1f4dcc18"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.3.2+0/PaStiX.v6.3.2.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[PaStiX]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "162f531109480af19300aaa92b7dd112314f0bb2"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "c7cdeb4df14de5fb2f14ceed44058aa4cab24a80702fc1a8e9c6899157477738"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.3.2+0/PaStiX.v6.3.2.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[PaStiX]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b7ca776277046174a83a432e771af0279c54f81c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "c7309d9627cf99afafaeba4f7524c1439e59e8ed608c5cc83ab0bccad9a71208"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.3.2+0/PaStiX.v6.3.2.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[PaStiX]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "19d86102861ea0cc7370e4c52582ed957caf6465"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "3bffc19fe5236e468328158be4a35faa2308866a995cc8060cbaf7d733200f58"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.3.2+0/PaStiX.v6.3.2.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[PaStiX]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5e3eff7d414fad10a81044db4765d53985a2d271"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "a0332d3a07563d2b6b91dd2da20adc40444ed50eb572a4abb1b3102a54baa643"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.3.2+0/PaStiX.v6.3.2.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[PaStiX]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "df059520164adb926e84f3399cbca068f16aabfc"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "1d42181c4598a5c4bb5e8409cccc75f3f30fe9a4d5c0cb4fec01d8878a30574f"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.3.2+0/PaStiX.v6.3.2.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[PaStiX]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d72c32cef8ce2314f3a9da5c59995c348d20df75"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "a5a22975b61c1a326a0919b39a1c266c63927017f05586070410a9a0bc0448fb"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.3.2+0/PaStiX.v6.3.2.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[PaStiX]]
arch = "i686"
git-tree-sha1 = "3cfa6679e67bb6a670f48c7e12f8accf7c4f548d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "7423d269e3286320e7780f7f1b05e8a463fbe114cf7ecfc3fb9437e8198b875f"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.3.2+0/PaStiX.v6.3.2.i686-linux-gnu-libgfortran4.tar.gz"
[[PaStiX]]
arch = "i686"
git-tree-sha1 = "970c375ab5670e6f48f8560dccdc451fbeb8bb6b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "a5bc9387322ebd44382e5c964775964d313e87f0eb315f32730bb7a7c4bc76c9"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.3.2+0/PaStiX.v6.3.2.i686-linux-gnu-libgfortran5.tar.gz"
[[PaStiX]]
arch = "i686"
git-tree-sha1 = "02117cdb019a71bd6a3e5271d920dd8707208619"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "17e8cf378acc6846e5eb76cd1f2bb7d7f588d5ab095c6f47cdc583c2c313cc68"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.3.2+0/PaStiX.v6.3.2.i686-linux-musl-libgfortran4.tar.gz"
[[PaStiX]]
arch = "i686"
git-tree-sha1 = "bc5173723aad6f2518d165cda6528e16d1468f8b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "be79c72967af0c7c1c2568b5422d1699ea934215550ef20d0b28d9e92ca5ebb1"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.3.2+0/PaStiX.v6.3.2.i686-linux-musl-libgfortran5.tar.gz"
[[PaStiX]]
arch = "i686"
git-tree-sha1 = "c118ef937e2bd3293e97b7f168c15b8addb6b25a"
libgfortran_version = "4.0.0"
os = "windows"

    [[PaStiX.download]]
    sha256 = "26531bc35044e37dbe7ba0a072dd448af9948e58b1da85e10bc1cb96284944ff"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.3.2+0/PaStiX.v6.3.2.i686-w64-mingw32-libgfortran4.tar.gz"
[[PaStiX]]
arch = "i686"
git-tree-sha1 = "3c8d23cd8176515806ee5f47c89c98d8d9f0b4ac"
libgfortran_version = "5.0.0"
os = "windows"

    [[PaStiX.download]]
    sha256 = "47af681d77cede1019ebf3c5b8aedf8b9c50e1c7fc4a3f81121a661611c82eab"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.3.2+0/PaStiX.v6.3.2.i686-w64-mingw32-libgfortran5.tar.gz"
[[PaStiX]]
arch = "powerpc64le"
git-tree-sha1 = "f84ca0b653a12ea51b35a5cc27f8af00ec23ed73"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "e42bffad05b58d4d589073666e21e9078185cc9aad777005743d3cb7f3803b82"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.3.2+0/PaStiX.v6.3.2.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[PaStiX]]
arch = "powerpc64le"
git-tree-sha1 = "4993c6e99cce1f64443721bfc21fc620b58edf9e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "1db5635e744f27916dd70930fc61a9ca9900b2da6e29bddaaf5c6b9557fc2acf"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.3.2+0/PaStiX.v6.3.2.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[PaStiX]]
arch = "x86_64"
git-tree-sha1 = "a134ff49505758d6f5629029baadeed557df1d10"
libgfortran_version = "4.0.0"
os = "macos"

    [[PaStiX.download]]
    sha256 = "de87522dd69f10f1ed83b3158d9546d56c389e279576e46ef5ef0597620118d1"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.3.2+0/PaStiX.v6.3.2.x86_64-apple-darwin-libgfortran4.tar.gz"
[[PaStiX]]
arch = "x86_64"
git-tree-sha1 = "ced70977df76ddf449915d6b886e6675cf3a829e"
libgfortran_version = "5.0.0"
os = "macos"

    [[PaStiX.download]]
    sha256 = "ec08a1bdaf3071f2ce7e5140a086aaa649481869c2f97d1ac9ebbdd4811f3bfb"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.3.2+0/PaStiX.v6.3.2.x86_64-apple-darwin-libgfortran5.tar.gz"
[[PaStiX]]
arch = "x86_64"
git-tree-sha1 = "a118fecc507ccae32b8c4c4abb7aa70b8b0d2849"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "848b47bfacb513e0f92f3956579bd0bf8ff7708ba1151b00639706cf81c3718c"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.3.2+0/PaStiX.v6.3.2.x86_64-linux-gnu-libgfortran4.tar.gz"
[[PaStiX]]
arch = "x86_64"
git-tree-sha1 = "fc8721837deb6df9009be9c9a5a34aba0cfeec7a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "fe487ca7890bdfceb1d2489c2909db02e69f65f81c84c8a1ff29515f3b8d2d5b"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.3.2+0/PaStiX.v6.3.2.x86_64-linux-gnu-libgfortran5.tar.gz"
[[PaStiX]]
arch = "x86_64"
git-tree-sha1 = "9f3c00a09cf1b7be86fcbc4f31ecc4a3a1519fbb"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "198900b6a8e2efdbba8c02cc08b8435281c0b17366f3d42eaa302dafda2fadc9"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.3.2+0/PaStiX.v6.3.2.x86_64-linux-musl-libgfortran4.tar.gz"
[[PaStiX]]
arch = "x86_64"
git-tree-sha1 = "b5f00e1fd8bb758ee98f2d9d65bcfe0b7329ddef"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "7445ff83a205060d425054f89cdb77b3aa00a44bd45b230cddd2458b9ef115cf"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.3.2+0/PaStiX.v6.3.2.x86_64-linux-musl-libgfortran5.tar.gz"
[[PaStiX]]
arch = "x86_64"
git-tree-sha1 = "f7946d1a24ec3b64aa1b90713c5e45e2c40750e3"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[PaStiX.download]]
    sha256 = "a482094b73702d5770055f90dc8802050ebc163a27fb37656d8417cd8b9954a0"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.3.2+0/PaStiX.v6.3.2.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[PaStiX]]
arch = "x86_64"
git-tree-sha1 = "187d844c32c62c87a0a0ddd5b5952ac749285238"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[PaStiX.download]]
    sha256 = "ea4aad9b5d8d64c5708d4571605eedca3859d5c5fa5888c7fe2290537670ae73"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.3.2+0/PaStiX.v6.3.2.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[PaStiX]]
arch = "x86_64"
git-tree-sha1 = "a2f4f0644135be1811a756ccae8c2932ff138664"
libgfortran_version = "4.0.0"
os = "windows"

    [[PaStiX.download]]
    sha256 = "0f2c024f64251c80d3c0618b2ded9d8291f7a8d14d0d0864f5d4b7074c91f1c0"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.3.2+0/PaStiX.v6.3.2.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[PaStiX]]
arch = "x86_64"
git-tree-sha1 = "2a10b93af04e644720681203ff33b06dcca6840e"
libgfortran_version = "5.0.0"
os = "windows"

    [[PaStiX.download]]
    sha256 = "a7538b9d3f2bc114fc6a6dc9b22422f471808170140b6318114f77ea9813f729"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.3.2+0/PaStiX.v6.3.2.x86_64-w64-mingw32-libgfortran5.tar.gz"
