[[PaStiX]]
arch = "aarch64"
git-tree-sha1 = "7ea362d7e115cdf665159e8015521bac2dca78c4"
libgfortran_version = "5.0.0"
os = "macos"

    [[PaStiX.download]]
    sha256 = "72e712f1aeecf2a611f29956a452a387d906168df587138935368ab628a1f53a"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.4.0+0/PaStiX.v6.4.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[PaStiX]]
arch = "aarch64"
git-tree-sha1 = "e95690f9fd82598d2eb81f2732e5de1533823245"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "b0813506ad4367ee0be3cf7153236027b8ff8a515972b0d1a306a94c5330f114"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.4.0+0/PaStiX.v6.4.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[PaStiX]]
arch = "aarch64"
git-tree-sha1 = "843d1a198def6502716b707c9602a53c0b3d13db"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "97a3230c5b6c83410c007d0deec846120cf4c50a06758989a629e2812bf71f05"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.4.0+0/PaStiX.v6.4.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[PaStiX]]
arch = "aarch64"
git-tree-sha1 = "739c403dee9f2a1a45daaa0f71d798ea10656ae5"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "89010280f9f1b5294147c98be1142679468a253a9e820d94c65321488204dc15"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.4.0+0/PaStiX.v6.4.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[PaStiX]]
arch = "aarch64"
git-tree-sha1 = "2f062c598d186eb1fe1cabc82c4a61d10bb44354"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "ab02b26721c87214ff65bbf9de78ce6a23e6dfa1f20ccb2edde43f28dca58249"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.4.0+0/PaStiX.v6.4.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[PaStiX]]
arch = "aarch64"
git-tree-sha1 = "25dc6c03d7eef2926414ba4c30be49eac5d8ded5"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[PaStiX.download]]
    sha256 = "49f2d2e29c56db2b802680ccbf73b24a62ddf0afcb5b148ad37927c35b004a07"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.4.0+0/PaStiX.v6.4.0.aarch64-unknown-freebsd-libgfortran4.tar.gz"
[[PaStiX]]
arch = "aarch64"
git-tree-sha1 = "ca0091bcd1f21a80ae72623a04919d2c1b9d41b6"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[PaStiX.download]]
    sha256 = "30fa213a97e84ee14967bd9ac8b55ba26d9979eb9237f510d11b729644733548"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.4.0+0/PaStiX.v6.4.0.aarch64-unknown-freebsd-libgfortran5.tar.gz"
[[PaStiX]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a6f2d08526673e1ca66cd4c20c56b68d203d3c26"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "1fcf9df95f21795f315a953f9b74c0e421b25f8845044e0397be3b75f38c71e8"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.4.0+0/PaStiX.v6.4.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[PaStiX]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a0846ed1f8eb7f4128d5b0e94302e78cbea091ed"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "45f7b72e1f528aee2c2d008ecb08f75261da88c4b34e7d33e7f8a99915f3c815"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.4.0+0/PaStiX.v6.4.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[PaStiX]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f62325df1e6c2249a953838f6c695c7224c8c412"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "3cb49a625d44556cfbd1a2c676725c3bac18778a6de9ee7181140c3ca37e7c39"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.4.0+0/PaStiX.v6.4.0.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[PaStiX]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5f7c79ea5666086ffe4cecb4a8c025b0a145cd99"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "f981e7932bbcd260ca6455fa5541ec9b1d18c63c862f2f7c14e2949c95ea8802"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.4.0+0/PaStiX.v6.4.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[PaStiX]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0f7d05f37d79184657ca20830d12d488ed3c40e8"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "5704ce91de6ece1446bc5f610b51963900b7bbd101584f1abd681b9771c956f3"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.4.0+0/PaStiX.v6.4.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[PaStiX]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8719c43cd41c6845127b13fa028e4a3004e45b77"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "a114de0131f88b03fff962a9bbe0d16dbb53f2260dd24cb752085cfb42306552"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.4.0+0/PaStiX.v6.4.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[PaStiX]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1d305fb2e83730d065165a8c649157de4457379c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "331a1f9afcb922aef3ed28deebe55d3c86809a6c1035e85abb3411e85165d4c8"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.4.0+0/PaStiX.v6.4.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[PaStiX]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "42700e477682ae46fe3c3a535508c2a19d4f7b76"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "febc938defad9bc22bad38b76c22a988709afe2ce9be931399ed37958e61b2e8"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.4.0+0/PaStiX.v6.4.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[PaStiX]]
arch = "i686"
git-tree-sha1 = "0c85ca0bd0b04e0d2cd75038f59ebb268f755afa"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "5682d6af9b1f689a16ddaef285f307ac07888f714d16c73fe537e411980bcc02"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.4.0+0/PaStiX.v6.4.0.i686-linux-gnu-libgfortran4.tar.gz"
[[PaStiX]]
arch = "i686"
git-tree-sha1 = "0fbdc368f0ee35bba254e37ab71fe5e26071db90"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "80f45fca04d1d14e4d26ae8264db040cf56b51efd22c147dc2d0d067e43e9721"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.4.0+0/PaStiX.v6.4.0.i686-linux-gnu-libgfortran5.tar.gz"
[[PaStiX]]
arch = "i686"
git-tree-sha1 = "05c511e78e1ce85d70fe758cdeb39faeb7720eae"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "3cf1ca571826e8aa4d3956894f12a2c442c567453d7105dc23e3164a243c4abe"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.4.0+0/PaStiX.v6.4.0.i686-linux-musl-libgfortran4.tar.gz"
[[PaStiX]]
arch = "i686"
git-tree-sha1 = "d3709dc88054244d3b620de98b410ebbaac38c30"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "9006e77694dddf72e297aad9fa211ba8f5de5fce36493c1df871ef9767b71bb5"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.4.0+0/PaStiX.v6.4.0.i686-linux-musl-libgfortran5.tar.gz"
[[PaStiX]]
arch = "i686"
git-tree-sha1 = "9b6dcdc8542a49b971759952eb7ff499fc2c9070"
libgfortran_version = "4.0.0"
os = "windows"

    [[PaStiX.download]]
    sha256 = "20b1483f240d9bf275da56259f22a99e5878524aad26f579475685e9d9de1da4"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.4.0+0/PaStiX.v6.4.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[PaStiX]]
arch = "i686"
git-tree-sha1 = "65e79203cec38198e68fedfeecac62ea54ec36e4"
libgfortran_version = "5.0.0"
os = "windows"

    [[PaStiX.download]]
    sha256 = "7e2c71798adbadc98b2d2dc60df6ceb52a98f9c0aaa9f7062e777da82a578794"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.4.0+0/PaStiX.v6.4.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[PaStiX]]
arch = "powerpc64le"
git-tree-sha1 = "c396a99e760024e491bd97a90958ee309ccfe893"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "108c2f98a3e651780f72e5d060810e8ef335991b1bbd92b72abf8090c3bf1392"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.4.0+0/PaStiX.v6.4.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[PaStiX]]
arch = "powerpc64le"
git-tree-sha1 = "ccb1a43021d1f48b628c24d46406011bbf5bea63"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "8af8aedadd56e5c822e7e0111f22d55dd10458b0219e297ea3d3df080467e194"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.4.0+0/PaStiX.v6.4.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[PaStiX]]
arch = "x86_64"
git-tree-sha1 = "0c1f9e137a9badcbbda7d0aaf6b1d0f7feccb232"
libgfortran_version = "4.0.0"
os = "macos"

    [[PaStiX.download]]
    sha256 = "175dacf8791e3a18cc75fd077f968e470ad6d0f63f4d42788c05cc927d8da868"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.4.0+0/PaStiX.v6.4.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[PaStiX]]
arch = "x86_64"
git-tree-sha1 = "74f047506ac22253b0b24b778e4ba842ad3a240f"
libgfortran_version = "5.0.0"
os = "macos"

    [[PaStiX.download]]
    sha256 = "a96c29a321fc935afeaccb1f4d5c040d4062e9a45157c939db98d79e61a0f710"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.4.0+0/PaStiX.v6.4.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[PaStiX]]
arch = "x86_64"
git-tree-sha1 = "b3895bf9d2481046f5f834a2a2e50f2a24ff5581"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "7543d9ee2223627ebdcfd918bb68a5d246a4a78b2c0fe77bd7a4e0ebe88f4658"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.4.0+0/PaStiX.v6.4.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[PaStiX]]
arch = "x86_64"
git-tree-sha1 = "38111d7bdaa72c68fdd502cf2ab845b985638da7"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "210519b2a3afd87e551d6d4231fbab4f504c4134f2d0547a6369abf962d11005"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.4.0+0/PaStiX.v6.4.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[PaStiX]]
arch = "x86_64"
git-tree-sha1 = "185f255aeef58dd721ba9351ad03c1131c2cf8cb"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "8e6f9a74c5e763c8155202411eb047a9c2a68c71997a597a9c8ae16d4946af08"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.4.0+0/PaStiX.v6.4.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[PaStiX]]
arch = "x86_64"
git-tree-sha1 = "0acbb238a14e449cb401c90edd3b07763c647254"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PaStiX.download]]
    sha256 = "f803ba49145566c07b433efd36faa97a080cd2c65a56219cf32f55b695441f33"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.4.0+0/PaStiX.v6.4.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[PaStiX]]
arch = "x86_64"
git-tree-sha1 = "6327a2adc2f312d0614d798027930f259d2d23bb"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[PaStiX.download]]
    sha256 = "f5ae0b10d9204881d4f636731b2bce35a153a7b9cd87bd87a59b8d1749c09b1d"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.4.0+0/PaStiX.v6.4.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[PaStiX]]
arch = "x86_64"
git-tree-sha1 = "adc46e4b69d5274c5c7c211f647782a99461f44c"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[PaStiX.download]]
    sha256 = "1b7f401d63b23f59c5c41c1fd20dadc3ec5645e2c6308557aceff755dcf662b8"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.4.0+0/PaStiX.v6.4.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[PaStiX]]
arch = "x86_64"
git-tree-sha1 = "885c39b10959cf1e1afc1215e7ecc1848639b74a"
libgfortran_version = "4.0.0"
os = "windows"

    [[PaStiX.download]]
    sha256 = "c015672754ee3cf05e9e947f91eed43fde29d8f41c1c6c3b913cf0a2aca44ce8"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.4.0+0/PaStiX.v6.4.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[PaStiX]]
arch = "x86_64"
git-tree-sha1 = "33b9cc4f27ec7cc22a14e9c891401922233799df"
libgfortran_version = "5.0.0"
os = "windows"

    [[PaStiX.download]]
    sha256 = "853a11174a04765c8acc82a523e7438fac70109f0d34b607f88a354827195f37"
    url = "https://github.com/JuliaBinaryWrappers/PaStiX_jll.jl/releases/download/PaStiX-v6.4.0+0/PaStiX.v6.4.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
