# Autogenerated wrapper script for PaStiX_jll for aarch64-apple-darwin-libgfortran5
export libpastix, libpastixf, libspm, libspmf

using CompilerSupportLibraries_jll
using METIS_jll
using SCOTCH_jll
using Hwloc_jll
using libblastrampoline_jll
JLLWrappers.@generate_wrapper_header("PaStiX")
JLLWrappers.@declare_library_product(libpastix, "@rpath/libpastix.6.4.dylib")
JLLWrappers.@declare_library_product(libpastixf, "@rpath/libpastixf.6.dylib")
JLLWrappers.@declare_library_product(libspm, "@rpath/libspm.1.dylib")
JLLWrappers.@declare_library_product(libspmf, "@rpath/libspmf.1.dylib")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, METIS_jll, SCOTCH_jll, Hwloc_jll, libblastrampoline_jll)
    JLLWrappers.@init_library_product(
        libpastix,
        "lib/libpastix.6.4.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libpastixf,
        "lib/libpastixf.6.4.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libspm,
        "lib/libspm.1.2.4.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libspmf,
        "lib/libspmf.1.2.4.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
